# Generated by Django 3.1.7 on 2021-05-20 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hb_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='do_it',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='start_day',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 20, 10, 54, 34, 409714)),
        ),
    ]
