# Generated by Django 3.1.7 on 2021-05-20 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hb_main', '0002_auto_20210520_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='do_it_list',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='start_day',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 20, 11, 25, 13, 974777)),
        ),
    ]
