# Generated by Django 3.1.7 on 2021-05-25 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hb_main', '0003_auto_20210520_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='end_Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_day', models.DateTimeField(default=datetime.datetime(2021, 5, 26, 1, 58, 26, 161921))),
                ('do_it_list', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='habit',
            name='start_day',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 1, 58, 26, 161921)),
        ),
    ]
