# Generated by Django 3.1.7 on 2021-05-25 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hb_main', '0004_auto_20210526_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='end',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='end_habit',
            name='start_day',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 2, 11, 5, 285593)),
        ),
        migrations.AlterField(
            model_name='habit',
            name='start_day',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 2, 11, 5, 285593)),
        ),
    ]
